sudo: false
language: node_js
node_js:
  - "8"

os:
  - linux
  - osx

git:
  depth: 300

after_success:
  - npm run coverage:ci

jobs:
  include:
    - stage: commit linting
      before_install:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
      # --ignore-scripts is disabling the postinstall script
      # which would run relatively slow "lerna bootstrap"
      install: npm install --ignore-scripts
      script: /bin/bash ./bin/lint-commits.sh
      after_success: skip
      os:
        - linux

branches:
  only:
    - master
